name: qualidadecompdca
description: "Gestão de Procedimentos."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  provider: ^6.1.2
  fl_chart: ^0.68.0
  flutter_native_splash: ^2.4.0
  flutter_splash_screen: ^3.0.0
  google_sign_in: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
